/* Интерактивная игра. Только стандартный JavaScript, без сторонних библиотек. */
(function(){
'use strict';
const D=window.RPG_DATA, KEY='ashlands-rpg-save-v1', OFFLINE=document.body.dataset.offline==='true';
const $=id=>document.getElementById(id);
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const zoneById=id=>D.zones.find(z=>z.id===id);
const recipeById=id=>D.guilds.flatMap(g=>g.recipes).find(r=>r.id===id);
let state=null, selectedClass='warrior', selectedGuild='smiths', selectedZone='city';
function load(){try{const s=JSON.parse(localStorage.getItem(KEY));return s&&s.hero&&D.classes[s.hero.cls]?s:null}catch{return null}}
function save(){if(state)localStorage.setItem(KEY,JSON.stringify(state))}
function newHero(name,cls){let base=D.classes[cls].stats;return {hero:{name:name.trim().slice(0,22)||'Странник',cls,level:1,xp:0,hp:base.hp,mana:base.mana},ingredients:{},items:{},potions:{},equipped:{weapon:null,armor:null},lastSelected:'city',activeBattle:null}}
function getStats(){if(!state)return null;const h=state.hero,base=D.classes[h.cls].stats,lv=h.level-1;const st={hp:base.hp+lv*12,mana:base.mana+lv*5,attack:base.attack+lv*3,defense:base.defense+Math.floor(lv*1.3)};for(const slot of ['weapon','armor']){const item=recipeById(state.equipped?.[slot]);if(item&&item.bonus)for(const [key,val] of Object.entries(item.bonus))st[key]=(st[key]||0)+val}return st}
function xpNeed(level){return 50+level*30}
function refreshPill(){const pill=$('player-pill');if(!pill)return;if(!state){pill.textContent='Новый странник';return}const c=D.classes[state.hero.cls];pill.innerHTML=`<span>${c.icon}</span><span><b>${escapeHtml(state.hero.name)}</b> · ур. ${state.hero.level}</span>`}
function toast(message){document.querySelector('.toast')?.remove();const div=document.createElement('div');div.className='toast';div.setAttribute('role','status');div.textContent=message;document.body.append(div);setTimeout(()=>div.remove(),3500)}
function goTo(page){if(OFFLINE){if(location.hash==='#'+page){showOfflinePage()}else location.hash='#'+page}else location.href=(page==='home'?'index':page)+'.html'}
function requireHero(){if(!state){goTo('home');return false}return true}
function rest(){if(!state)return;state.hero.hp=getStats().hp;state.hero.mana=getStats().mana;state.activeBattle=null;save();toast('В городе Рубеж здоровье и мана полностью восстановлены.');return true}
function bonusText(b){const labels={attack:'атака',defense:'защита',hp:'здоровье',mana:'мана'};return Object.entries(b||{}).map(([k,v])=>`+${v} ${labels[k]||k}`).join(' · ')}
function renderHome(){const grid=$('class-grid');if(!grid)return;
 function renderClasses(){grid.innerHTML=Object.entries(D.classes).map(([id,c])=>`<button type="button" class="class-card ${id===selectedClass?'selected':''}" data-class="${id}" aria-pressed="${id===selectedClass}"><div class="class-icon">${c.icon}</div><h3>${c.name}</h3><span class="tiny">${c.tagline}</span><p>${c.description}</p><div class="statline">❤️ ${c.stats.hp} · 💧 ${c.stats.mana} · ⚔️ ${c.stats.attack} · 🛡️ ${c.stats.defense}</div></button>`).join('');grid.querySelectorAll('[data-class]').forEach(b=>b.addEventListener('click',()=>{selectedClass=b.dataset.class;renderClasses()}))}
 renderClasses();$('create-hero').addEventListener('click',()=>{if(state&&!confirm('Заменить текущего героя и потерять весь прогресс?'))return;state=newHero($('hero-name').value,selectedClass);save();goTo('map')});
 if(state){const c=D.classes[state.hero.cls],s=getStats(),h=state.hero;const panel=$('existing-game');panel.hidden=false;panel.innerHTML=`<div class="hero-preview"><div class="hero-avatar">${c.icon}</div><div><span class="eyebrow">Продолжить путешествие</span><h2>${escapeHtml(h.name)} · ${c.name} · ур. ${h.level}</h2><p>❤️ ${h.hp}/${s.hp} · 💧 ${h.mana}/${s.mana} · ⚔️ ${s.attack} · 🛡️ ${s.defense}</p></div></div><div class="stat-label"><span>До следующего уровня</span><span>${h.xp}/${xpNeed(h.level)} опыта</span></div><div class="progress xp"><span style="width:${Math.min(100,h.xp/xpNeed(h.level)*100)}%"></span></div><div class="btn-row" style="margin-top:19px"><a class="btn" href="map.html">🗺️ Продолжить на карте</a><a class="btn secondary" href="guilds.html">⚒️ Создать снаряжение</a><button class="btn danger" id="reset-game">Сбросить сохранение</button></div>`;
 $('new-game').hidden=true;$('reset-game').addEventListener('click',()=>{if(confirm('Удалить персонажа, все ингредиенты и ремесленные вещи?')){localStorage.removeItem(KEY);state=null;OFFLINE?showOfflinePage():location.reload()}})}
}
function renderMap(){if(!requireHero())return;const groups=document.querySelectorAll('.map-zone');selectedZone=zoneById(state.lastSelected)?state.lastSelected:'city';
 function selectZone(id){const z=zoneById(id);if(!z)return;selectedZone=id;state.lastSelected=id;save();groups.forEach(g=>g.classList.toggle('selected',g.dataset.zone===id));const target=$('zone-panel');const danger=z.danger===0?'green':z.danger>=5?'red':z.danger>=3?'gold':'violet';
 const header=`<span class="eyebrow">${escapeHtml(z.subtitle)}</span><div class="zone-header"><div class="zone-symbol">${z.icon}</div><div><h2 class="zone-title">${escapeHtml(z.name)}</h2><span class="tag ${danger}">${z.danger===0?'Нет врагов':'Уровни '+z.level}</span></div></div><p class="zone-description">${escapeHtml(z.description)}</p><p class="tiny"><b>Местность:</b> ${escapeHtml(z.environment)}</p><div class="info-block"><b>Совет путешественнику:</b> ${escapeHtml(z.tips)}</div>`;
 if(z.id==='city'){target.innerHTML=header+`<div class="hr"></div><h3 class="section-title">Городские службы</h3><p class="muted">Здесь безопасно. Все четыре гильдии создают снаряжение исключительно из добытых ингредиентов.</p><div class="btn-row"><button class="btn" id="rest-city">❤️‍🩹 Восстановить здоровье и ману</button><a class="btn secondary" href="guilds.html">⚒️ Посетить гильдии</a></div><div class="hr"></div><span class="tag green">🏰 Стартовая локация</span>`;$('rest-city').addEventListener('click',rest)}
 else{const mons=z.mobs.map((id,i)=>{const m=D.mobs[id];return `<details class="mob-accordion" ${i===0?'open':''}><summary><span class="mob-face">${m.icon}</span><span class="mob-txt"><strong>${escapeHtml(m.name)}</strong><small>Ур. ${m.level} · ❤️ ${m.hp} · ⚔️ ${m.attack} · 🛡️ ${m.defense}</small></span></summary><div class="mob-accordion-body"><p>${escapeHtml(m.description)}</p><div class="detail-subtitle">⚡ Поведение в бою</div><p>${escapeHtml(m.behavior)}</p><div class="detail-subtitle">🎯 Особенность и слабость</div><p><b>${escapeHtml(m.abilityName)}.</b> ${escapeHtml(m.weakness)}</p><div class="detail-subtitle">🎒 Добыча — только ингредиенты</div>${m.drops.map(([n,p,min,max])=>`<div class="loot-mini"><span>${escapeHtml(n)} · ${min===max?min:min+'–'+max} шт.</span><b>${p}%</b></div>`).join('')}<p class="tiny">Каждый ингредиент разыгрывается отдельно после победы. Шансы не складываются.</p><button class="btn wide start-battle" data-mob="${id}" data-zone="${z.id}">⚔️ Напасть · +${m.xp} опыта</button></div></details>`}).join('');target.innerHTML=header+`<div class="hr"></div><h3 class="section-title">Враждебные существа · ${z.mobs.length}</h3><p class="tiny">Открой карточку, чтобы узнать тактику и шанс получения ингредиентов.</p>${mons}`;target.querySelectorAll('.start-battle').forEach(btn=>btn.addEventListener('click',()=>startBattle(btn.dataset.mob,btn.dataset.zone)))}
 }
 groups.forEach(g=>{g.addEventListener('click',()=>selectZone(g.dataset.zone));g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectZone(g.dataset.zone)}})});$('rest-on-map').addEventListener('click',()=>{rest();selectZone('city')});selectZone(selectedZone);
 if(state.activeBattle&&!state.activeBattle.result){const notice=document.createElement('div');notice.className='info-block';notice.innerHTML=`Идёт незавершённый бой. <a href="battle.html" style="color:#ead4ff;text-decoration:underline;font-weight:bold">Вернуться к сражению →</a>`;$('zone-panel').prepend(notice)}
}
function startBattle(mobId,zoneId){if(!state||!D.mobs[mobId]||!zoneById(zoneId)?.mobs.includes(mobId))return;const stats=getStats();if(state.hero.hp<=0){toast('Сперва восстанови здоровье в городе.');return}const m=D.mobs[mobId];state.activeBattle={mobId,zoneId,mobHp:m.hp,turn:0,effect:null,result:null,logs:[{text:`Вы встретили противника: ${m.name}. Бой начался!`,kind:'item'}]};save();goTo('battle')}
function gainExperience(num){const h=state.hero;h.xp+=num;let raised=0;while(h.xp>=xpNeed(h.level)){h.xp-=xpNeed(h.level);h.level++;raised++}if(raised){h.hp=getStats().hp;h.mana=getStats().mana}return raised}
function addLog(text,kind){const b=state.activeBattle;b.logs.push({text,kind:kind||''});b.logs=b.logs.slice(-35)}
function dice(min,max){return Math.floor(Math.random()*(max-min+1))+min}
function playerDamage(power,def,ignore){const stats=getStats();return Math.max(1,Math.round(stats.attack*power+ dice(-2,3)-def*(ignore?.13:.48)))}
function monsterAttack(guard){const b=state.activeBattle,m=D.mobs[b.mobId],h=state.hero;let damage=Math.max(1,Math.round(m.attack+dice(-3,4)-getStats().defense*.65));let special=b.turn%3===0;
 if(special){if(m.ability==='rake'){damage=Math.round(damage*1.65);addLog(`${m.name}: «${m.abilityName}» — мощная атака!`,'hurt')}else if(m.ability==='pierce'){damage=Math.round(m.attack*1.25+dice(-2,3)-getStats().defense*.15);addLog(`${m.name}: «${m.abilityName}» пробивает броню!`,'hurt')}else if(m.ability==='drain'){const amount=Math.min(h.mana,10+Math.floor(m.level*.45));h.mana-=amount;addLog(`${m.name} использует «${m.abilityName}» и забирает ${amount} маны.`,'hurt')}else if(m.ability==='poison'||m.ability==='burn'){b.effect={type:m.ability,rounds:2,value:m.ability==='burn'?Math.max(5,Math.round(m.level*.5)):Math.max(4,Math.round(m.level*.33))};addLog(`${m.name} применяет «${m.abilityName}»: эффект действует 2 хода.`,'hurt')}}
 if(guard){damage=Math.ceil(damage*.45);addLog('Защитная стойка смягчила удар.','item')}h.hp=Math.max(0,h.hp-damage);addLog(`${m.name} наносит ${damage} урона герою.`,'hurt');
 if(h.hp>0&&b.effect){h.hp=Math.max(0,h.hp-b.effect.value);addLog(`${b.effect.type==='burn'?'Ожог':'Яд'} наносит ${b.effect.value} урона (${b.effect.rounds} ход. эффекта).`,'hurt');b.effect.rounds--;if(b.effect.rounds<=0)b.effect=null}
 if(h.hp<=0){b.result='loss';addLog(`${h.name} проиграл бой. Вернись в город и восстанови силы.`,'hurt')}
}
function performBattle(action){const b=state.activeBattle;if(!b||b.result)return;const m=D.mobs[b.mobId],h=state.hero,c=D.classes[h.cls];let guard=false;
 if(action==='attack'){const damage=playerDamage(1,m.defense,false);b.mobHp=Math.max(0,b.mobHp-damage);h.mana=Math.min(getStats().mana,h.mana+4);addLog(`${h.name} атакует и наносит ${damage} урона. +4 маны.`)}
 else if(action==='skill'){if(h.mana<c.skill.mana){toast('Недостаточно маны. Используй обычную атаку или мановый настой.');return}h.mana-=c.skill.mana;const damage=playerDamage(c.skill.power,m.defense,c.skill.ignoreDefense);b.mobHp=Math.max(0,b.mobHp-damage);addLog(`${h.name} использует «${c.skill.name}» и наносит ${damage} урона!`,'item')}
 else if(action==='defend'){guard=true;const amount=Math.min(9,getStats().mana-h.mana);h.mana+=amount;addLog(`${h.name} защищается и восполняет ${amount} маны.`,'item')}
 else if(action==='healthPotion'||action==='manaPotion'){if(!(state.potions[action]>0)){toast('Эликсир отсутствует. Создай его в гильдии алхимиков.');return}const rec=recipeById(action),max=getStats(),k=action==='healthPotion'?'hp':'mana',current=h[k],restored=Math.min(rec.effect[k],max[k]-current);if(restored===0){toast('Этот ресурс уже полностью восстановлен.');return}state.potions[action]--;h[k]+=restored;addLog(`${h.name} использует «${rec.name}»: +${restored} ${k==='hp'?'здоровья':'маны'}.`,'item')}
 else return;
 b.turn++;
 if(b.mobHp<=0){b.result='win';const loot=[];for(const [name,chance,min,max] of m.drops)if(Math.random()*100<chance){const qty=dice(min,max);state.ingredients[name]=(state.ingredients[name]||0)+qty;loot.push({name,qty})}b.loot=loot;b.xp=m.xp;const raised=gainExperience(m.xp);b.levels=raised;addLog(`Победа над ${m.name}! Получено ${m.xp} опыта. ${raised?'Повышение уровня: +'+raised+'.':''}`,'win');if(loot.length)addLog('Получено: '+loot.map(x=>`${x.name} ×${x.qty}`).join(', '),'item');else addLog('На этот раз ингредиенты не выпали.','item')}
 else monsterAttack(guard);
 save();refreshPill();renderBattle()}
function renderBattle(){if(!requireHero())return;let b=state.activeBattle;
 if(!b){$('fight-stage').innerHTML='<div class="card-pad">Нет активного боя. Выбери противника на карте мира.</div>';$('battle-actions').innerHTML='<a class="btn" href="map.html">Открыть карту</a>';$('battle-details').innerHTML='<p class="muted">Выбери территорию на карте, чтобы увидеть её обитателей.</p>';return}
 const m=D.mobs[b.mobId],z=zoneById(b.zoneId),h=state.hero,s=getStats(),c=D.classes[h.cls];$('battle-heading').textContent='Сражение: '+m.name;$('battle-location').textContent=z.name+' · враг '+m.level+' уровня';
 function hpBar(name,val,max,cls){return `<div class="stat-label"><span>${name}</span><b>${Math.max(0,val)} / ${max}</b></div><div class="progress ${cls||''}"><span style="width:${Math.max(0,Math.min(100,val/max*100))}%"></span></div>`}
 $('fight-stage').innerHTML=`<div class="fight-character"><div class="portrait">${c.icon}</div><h3>${escapeHtml(h.name)}</h3><span class="tag green">${c.name} · ур. ${h.level}</span><div style="margin-top:13px">${hpBar('❤️ Здоровье',h.hp,s.hp)}${hpBar('💧 Мана',h.mana,s.mana,'mana')}</div></div><div class="versus">VS</div><div class="fight-character"><div class="portrait">${m.icon}</div><h3>${escapeHtml(m.name)}</h3><span class="tag red">Враг · ур. ${m.level}</span><div style="margin-top:13px">${hpBar('❤️ Здоровье',b.mobHp,m.hp,'danger')}<div class="stat-label"><span>Атака / защита</span><b>${m.attack} / ${m.defense}</b></div></div></div>`;
 const actions=$('battle-actions'),out=$('battle-result');if(b.result){actions.innerHTML='<a class="btn" href="map.html">← Выбрать следующего врага</a><a class="btn secondary" href="guilds.html">⚒️ Вернуться в город</a>';if(b.result==='win'){out.innerHTML=`<div class="battle-result"><h3>🏆 Победа! +${b.xp||m.xp} опыта</h3>${b.levels?`<p>🎉 Повышение уровня: +${b.levels}!</p>`:''}<b>Ингредиенты:</b><ul>${(b.loot||[]).length?(b.loot||[]).map(x=>`<li>${escapeHtml(x.name)} ×${x.qty}</li>`).join(''):'<li>В этот раз ничего не выпало.</li>'}</ul><span class="tiny">Экипировка с врагов никогда не выпадает.</span></div>`}else out.innerHTML='<div class="battle-result loss"><h3>💀 Поражение</h3><p>Ты потерял все очки здоровья. Возвращайся в город Рубеж и бесплатно отдохни, прежде чем снова отправиться в путь.</p></div>'}
 else{out.innerHTML='';actions.innerHTML=`<button class="btn" data-action="attack">⚔️ Атака · +4 маны</button><button class="btn secondary" data-action="skill">✨ ${c.skill.name} · −${c.skill.mana} маны</button><button class="btn secondary" data-action="defend">🛡️ Защита · +9 маны</button><button class="btn secondary" data-action="healthPotion">❤️ Эликсир ×${state.potions.healthPotion||0}</button><button class="btn secondary" data-action="manaPotion">💧 Настой ×${state.potions.manaPotion||0}</button>`;actions.querySelectorAll('[data-action]').forEach(x=>x.addEventListener('click',()=>performBattle(x.dataset.action)))}
 $('battle-log').innerHTML=b.logs.slice().reverse().map(x=>`<div class="log-entry ${x.kind||''}">${escapeHtml(x.text)}</div>`).join('');
 $('battle-details').innerHTML=`<span class="eyebrow">Досье на противника</span><div class="zone-header"><div class="zone-symbol">${m.icon}</div><div><h2 class="zone-title">${escapeHtml(m.name)}</h2><span class="tag red">Уровень ${m.level}</span></div></div><div class="mob-details-stats"><span class="tag">❤️ ${m.hp}</span><span class="tag">⚔️ ${m.attack}</span><span class="tag">🛡️ ${m.defense}</span><span class="tag gold">✦ ${m.xp} опыта</span></div><p>${escapeHtml(m.description)}</p><div class="detail-subtitle">⚡ Тактика</div><p>${escapeHtml(m.behavior)}</p><div class="detail-subtitle">🎯 Уязвимость</div><p>${escapeHtml(m.weakness)}</p><div class="detail-subtitle">🎒 Вероятность добычи</div>${m.drops.map(([name,p,min,max])=>`<div class="loot-row"><span>${escapeHtml(name)} · ${min===max?min:min+'–'+max} шт.</span><b>${p}%</b></div>`).join('')}<div class="info-block" style="margin-top:18px">Готовая экипировка не выпадает. Все шансы независимы.</div>`
}
function renderGuilds(){if(!requireHero())return;function render(){const g=D.guilds.find(x=>x.id===selectedGuild)||D.guilds[0];$('guild-list').innerHTML=D.guilds.map(x=>`<button type="button" class="guild-tab ${x.id===g.id?'active':''}" data-guild="${x.id}">${x.icon} ${x.name}</button>`).join('');$('guild-list').querySelectorAll('[data-guild]').forEach(e=>e.addEventListener('click',()=>{selectedGuild=e.dataset.guild;render()}));
 const ing=Object.entries(state.ingredients).filter(([,q])=>q>0).sort((a,b)=>a[0].localeCompare(b[0],'ru'));$('inventory-list').innerHTML=ing.length?ing.map(([n,q])=>`<span class="ingredient">${escapeHtml(n)} <b>×${q}</b></span>`).join(''):'<span class="muted" style="font-size:.84rem">Пока пусто. Сражайся с мобами и собирай материалы.</span>';
 $('equipment').innerHTML=['weapon','armor'].map(slot=>{const r=recipeById(state.equipped?.[slot]);const label=slot==='weapon'?'⚔️ Оружие':'🛡️ Броня';return `<div><span><b>${label}</b><br><span class="tiny">${r?escapeHtml(r.name)+' · '+bonusText(r.bonus):'Пустой слот'}</span></span></div>`}).join('');
 const crafted=Object.entries(state.items).filter(([,q])=>q>0).map(([id,q])=>recipeById(id)).filter(Boolean);
 $('guild-content').innerHTML=`<span class="eyebrow">Ремесло · Город Рубеж</span><h2 style="font-size:1.8rem;margin:8px 0 4px">${g.icon} ${escapeHtml(g.name)}</h2><p class="muted">${escapeHtml(g.description)}</p><div class="recipe-grid">${g.recipes.map(r=>{const enough=Object.entries(r.cost).every(([n,q])=>(state.ingredients[n]||0)>=q);const own=state.items[r.id]||0;const selected=state.equipped?.[r.slot]===r.id;return `<article class="recipe"><div class="recipe-title"><span class="face">${r.icon}</span><div><h3>${escapeHtml(r.name)}</h3><span class="tag violet">${r.slot==='consumable'?'Эликсир':r.slot==='weapon'?'Оружие':'Броня'}</span></div></div><p>${escapeHtml(r.description)}</p><div class="tiny" style="margin-bottom:10px;color:#f4d99c">${r.bonus?bonusText(r.bonus):'Эффект: '+(r.effect.hp?'+'+r.effect.hp+' здоровья':'+'+r.effect.mana+' маны')}</div><b class="small-head">Необходимые ингредиенты</b>${Object.entries(r.cost).map(([name,q])=>{const have=state.ingredients[name]||0;return `<div class="need"><span>${escapeHtml(name)}</span><span class="${have>=q?'sufficient':'insufficient'}">${have} / ${q}</span></div>`}).join('')}<button class="btn wide" data-craft="${r.id}" ${enough?'':'disabled'}>${enough?'⚒️ Создать':'Не хватает материалов'}</button>${r.slot==='consumable'?`<span class="tiny" style="margin-top:9px">В сумке: ${state.potions[r.id]||0}</span>`:own?`<button class="btn secondary wide slim" style="margin-top:8px" data-equip="${r.id}" ${selected?'disabled':''}>${selected?'✓ Надето':'Надеть (создано: '+own+')'}</button>`:''}</article>`}).join('')}</div>${crafted.length?`<div class="hr"></div><h3 class="section-title">Созданное снаряжение</h3><div class="inventory-list">${crafted.map(r=>`<span class="ingredient">${r.icon} ${escapeHtml(r.name)} ×${state.items[r.id]}</span>`).join('')}</div>`:''}`;
 $('guild-content').querySelectorAll('[data-craft]').forEach(e=>e.addEventListener('click',()=>{const r=recipeById(e.dataset.craft);if(!r||!Object.entries(r.cost).every(([name,q])=>(state.ingredients[name]||0)>=q))return;for(const [name,qty] of Object.entries(r.cost))state.ingredients[name]-=qty;if(r.slot==='consumable'){state.potions[r.id]=(state.potions[r.id]||0)+1}else{state.items[r.id]=(state.items[r.id]||0)+1;const old=getStats();state.equipped[r.slot]=r.id;const newer=getStats();state.hero.hp=Math.min(newer.hp,state.hero.hp+Math.max(0,newer.hp-old.hp));state.hero.mana=Math.min(newer.mana,state.hero.mana+Math.max(0,newer.mana-old.mana))}save();toast('Создано: '+r.name+'!');render()}));
 $('guild-content').querySelectorAll('[data-equip]').forEach(e=>e.addEventListener('click',()=>{const r=recipeById(e.dataset.equip);if(!r||!state.items[r.id])return;state.equipped[r.slot]=r.id;const stats=getStats();state.hero.hp=Math.min(state.hero.hp,stats.hp);state.hero.mana=Math.min(state.hero.mana,stats.mana);save();toast('Надето: '+r.name);render()}));
 }
 $('rest').addEventListener('click',()=>{rest();render()});render()}
function showOfflinePage(){const page=['home','map','battle','guilds'].includes(location.hash.slice(1))?location.hash.slice(1):'home';document.querySelectorAll('[data-view]').forEach(view=>{view.hidden=view.dataset.view!==page});const view=document.querySelector(`[data-view="${page}"]`);if(!view)return;view.innerHTML=offlineTemplates[page];document.querySelectorAll('.navlinks a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')==='#'+page));document.body.dataset.page=page;state=load();refreshPill();if(page==='home')renderHome();else if(page==='map')renderMap();else if(page==='battle')renderBattle();else if(page==='guilds')renderGuilds();window.scrollTo(0,0)}
const offlineTemplates={};
if(OFFLINE){document.querySelectorAll('[data-view]').forEach(v=>offlineTemplates[v.dataset.view]=v.innerHTML);window.addEventListener('hashchange',showOfflinePage);showOfflinePage()}
else{state=load();refreshPill();const page=document.body.dataset.page;if(page==='home')renderHome();else if(page==='map')renderMap();else if(page==='battle')renderBattle();else if(page==='guilds')renderGuilds()}
})();
