/* Тар-Моран: самостоятельный движок. Один ход — одно ручное действие. */
(function(root){'use strict';
const D=root.TM_DATA, slots=['weapon','armor','head','relic','boots','pet'];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n)), total=o=>Object.values(o).reduce((a,b)=>a+b,0);
class Game{
 constructor(state=null,rng=Math.random){this.rng=rng;this.s=state;}
 create(name,cls){if(!D.classes[cls])throw Error('Выберите класс.');const c=D.classes[cls];this.s={version:2,name:String(name).trim().slice(0,24)||'Странник',cls,level:1,xp:0,hp:c.hp,mana:c.mana,coins:100,rep:0,tier:1,room:'Рыночная площадь',day:1,hour:9,turns:0,curse:0,breath:0,inventory:{'Малое зелье HP':3,'Малое зелье маны':2,'Факел':1,[c.starter]:1},equipment:{weapon:c.starter},durability:{[c.starter]:100},upgrades:{},stats:{strength:0,agility:0,intellect:0,vitality:0,luck:0},statPoints:0,skillPoints:1,skills:{[cls+'0']:1},loadout:[cls+'0'],kills:{},explored:{},bosses:{},quests:{},choices:{},achievements:{},crafts:0,pickkills:0,flawless:0,trials:0,ng:0,ending:null,battle:null,feed:['Ты вошёл в Тар-Моран. Поговори с Корином в журнале заданий.'],flags:{}};return this.s;}
 say(t){this.s.feed.unshift(t);this.s.feed=this.s.feed.slice(0,35);return t;}
 need(v,msg){if(!v)throw Error(msg);}
 idle(){this.need(!this.s.battle||this.s.battle.result,'Сначала завершите бой.');}
 count(n){return this.s.inventory[n]||0;}
 add(n,q=1){this.need(D.items[n],`Неизвестный предмет: ${n}`);this.s.inventory[n]=this.count(n)+q;if(D.items[n].slot&&this.s.durability[n]===undefined)this.s.durability[n]=100;}
 remove(n,q){this.need(this.count(n)>=q,'Не хватает: '+n);this.s.inventory[n]-=q;if(!this.count(n)){for(const slot of slots)if(this.s.equipment[slot]===n)delete this.s.equipment[slot];}this.cap();}
 stats(){const s=this.s,c=D.classes[s.cls],lv=s.level-1;let x={hp:c.hp+lv*30+s.stats.vitality*12,mana:c.mana+lv*5+s.stats.intellect*3,attack:c.attack+lv*5+s.stats[c.primary]*2,defense:c.defense+lv*1.4+s.stats.strength*.3,crit:.05+s.stats.agility*.002,dodge:.02+s.stats.agility*.002,luck:s.stats.luck,block:0,poisonResist:0,darkResist:0,damageBoost:0,lifesteal:0};
 for(const n of Object.values(s.equipment)){const it=D.items[n];if(!it||!this.count(n)||(s.durability[n]??100)<=0)continue;for(const [k,v]of Object.entries(it.bonus))x[k]=(x[k]||0)+v;const u=s.upgrades[n]||0;x.attack+=it.slot==='weapon'?u*4:0;x.defense+=it.slot==='armor'?u*4:0;}
 for(const skill of D.skills.filter(a=>a.cls===s.cls&&a.passive))if(s.skills[skill.id])x[skill.effect]=(x[skill.effect]||0)+skill.amount*s.skills[skill.id];
 if(x.allBoost)for(const k of ['hp','mana','attack','defense'])x[k]*=1+x.allBoost;
 if(s.curse>=100&&!x.curseImmune){x.attack*=.75;x.defense*=.75;}
 for(const k of ['hp','mana','attack','defense'])x[k]=Math.round(x[k]);x.crit=clamp(x.crit,0,.75);x.dodge=clamp(x.dodge,0,.6);x.block=clamp(x.block,0,.6);return x;}
 cap(){if(!this.s)return;const st=this.stats();this.s.hp=clamp(this.s.hp,0,st.hp);this.s.mana=clamp(this.s.mana,0,st.mana);}
 xpNeed(){return 60*this.s.level+40;}
 xp(n){const s=this.s;s.xp+=n;let up=0;while(s.level<60&&s.xp>=this.xpNeed()){s.xp-=this.xpNeed();s.level++;s.statPoints+=3;s.skillPoints+=2;up++;}if(up){s.hp=this.stats().hp;s.mana=this.stats().mana;this.say('Новый уровень: '+s.level+'. Доступны характеристики и умения.');}return up;}
 tick(){const s=this.s;s.turns++;s.hour++;if(s.hour>=24){s.hour=0;s.day++;}if(s.breath>0)s.breath--;}
 discount(){const r=this.s.rep;return r>=300?.6:r>=200?.5:r>=150?.4:r>=100?.3:r>=50?.15:0;}
 gate(t){const s=this.s;if(t===1)return '';if(t<1||t>7)return 'Нет такого яруса';const levels=[1,5,10,15,20,25,30];if(s.level<levels[t-1])return 'Нужен уровень '+levels[t-1];if(!s.bosses[D.zones[t-2].boss])return 'Победите: '+D.mobs.find(m=>m.id===D.zones[t-2].boss).name;
 if(t===3&&!s.quests['2.1']?.done)return 'Завершите «Ключ от спуска» у Борина';if(t===4&&!s.quests['3.1']?.done)return 'Завершите «Сердце океана»';if(t===6&&!s.quests['5.1']?.done)return 'Завершите «Армия Мората»';if(t===7&&!s.quests['6.1']?.done)return 'Завершите «Правда о Бездне»';return '';}
 travel(t,room){this.idle();this.need(!this.gate(t),this.gate(t));this.need(D.zones[t-1].rooms.includes(room),'Нет такой локации.');if(t===2)this.need(this.count('Факел')||this.stats().light||this.s.cls==='mage','В шахтах нужен факел. Он продаётся у Корина.');if(room==='Подводные пещеры')this.need(this.count('Дыхание бездны')||this.stats().breath||this.s.breath>0,'Нужны Дыхание бездны или свиток дыхания.');this.s.tier=t;this.s.room=room;this.s.battle=null;this.tick();this.say('Переход: '+room);}
 rest(){this.idle();const s=this.s;s.tier=1;s.room='Рыночная площадь';s.hp=this.stats().hp;s.mana=this.stats().mana;s.curse=0;s.battle=null;this.tick();this.say('Отдых в Верхнем городе. Здоровье и мана восстановлены.');}
 explore(){this.idle();const s=this.s;this.need(s.hp>0,'Отдохните в городе.');if(s.room==='Подводные пещеры')this.need(this.count('Дыхание бездны')||this.stats().breath||s.breath>0,'Воздух закончился. Используйте свиток или вернитесь на пристань.');this.tick();s.explored[s.room]=(s.explored[s.room]||0)+1;let found=[];for(const [n,p,q]of D.gather[s.room]||[])if(this.rng()*100<p){this.add(n,q);found.push(n+' ×'+q);}if(s.tier===5&&!this.stats().curseImmune)s.curse=clamp(s.curse+8,0,100);if(s.tier===4&&!this.stats().fireImmune&&!this.stats().traps){s.hp=Math.max(1,s.hp-5);found.push('ловушка: −5 HP');}if(this.rng()<.1){s.flags.foxTier=s.tier;s.flags.foxDay=s.day;}this.say('Обыск: '+(found.join(', ')||'ничего не найдено.'));this.xp(4*s.tier);if(this.rng()<.22&&s.room!=='Рыночная площадь'&&s.room!=='Храм Забытых'){const pool=D.mobs.filter(m=>m.tier===s.tier&&!m.boss);this.start(pool[Math.floor(this.rng()*pool.length)].id);this.say('Шум привлёк врага.');}}
 solve(rune){this.idle();this.need(this.s.tier===4,'Руны находятся в Кузне.');const order=['Огонь','Молот','Печать'],idx=this.s.flags.runeStep||0;if(rune===order[idx]){this.s.flags.runeStep=idx+1;if(idx===2)this.s.flags.forgeOpen=true;this.say(idx===2?'Руны открыли Горн Бездны.':'Руна вспыхнула.')}else{this.s.flags.runeStep=0;this.s.hp=Math.max(1,this.s.hp-10);this.say('Неверный порядок. Руны погасли, −10 HP.');}}
 chance(drop){return clamp(drop[1]+(D.items[drop[0]].rarity===4?this.stats().luck*.5:0),0,100);}
 start(id,trial=false){this.idle();const s=this.s,m=D.mobs.find(x=>x.id===id);this.need(m,'Неизвестный противник.');this.need(s.hp>0,'Отдохните в городе.');this.need(trial||m.tier===s.tier,'Противник находится на другом ярусе.');if(m.name==='Кователь Кальдрас')this.need(s.flags.forgeOpen,'Откройте Горн, решив головоломку рун.');if(m.name==='Истинная форма Бездны')this.need(s.trials>=3,'Пройдите три боя Коридора Испытаний.');const st=this.stats(),max=(m.hp<0?st.hp*-m.hp:m.hp)*(1+s.ng*.35),attack=(m.name==='Эхо-копия'?st.attack*.8:m.name==='Отражение героя'?st.attack*.7:m.attack)*(1+s.ng*.25);s.battle={id,enemyHp:Math.round(max),maxHp:Math.round(max),attack:Math.round(attack),turn:0,cooldowns:{},enemyEffects:{},heroEffects:{},shield:0,damageTaken:0,logs:['Враг: '+m.name+'. Выберите действие.'],result:null,loot:[],trial};}
 startTrial(){this.idle();this.need(this.s.tier===7,'Испытания находятся на седьмом ярусе.');this.need(this.s.trials<3,'Испытания уже пройдены.');const names=['Каменный Страж','Мастер-кузнец','Король-Лич Морат'];this.start(D.mobs.find(m=>m.name===names[this.s.trials]).id,true);this.s.battle.maxHp=Math.round(900+this.s.trials*650);this.s.battle.enemyHp=this.s.battle.maxHp;this.s.battle.attack=40+this.s.trials*10;}
 log(t){const b=this.s.battle;b.logs.unshift(t);b.logs=b.logs.slice(0,60);}
 effect(target,name,turns,power){target[name]={turns,power};}
 intent(){const b=this.s.battle;if(!b||b.result)return '';const m=D.mobs.find(x=>x.id===b.id);return (b.turn+1)%3===0?'Мощный удар · защита снизит урон':m.name==='Королева Ползунов'&&(b.turn+1)%4===0?'Призыв ползунов':m.behavior;}
 act(action){const s=this.s,b=s.battle;this.need(b&&!b.result,'Нет активного боя.');const m=D.mobs.find(x=>x.id===b.id),st=this.stats();let guard=false,power=0,drain=0,skill=null;
 if(action.startsWith('skill:')){skill=D.skills.find(x=>x.id===action.slice(6));this.need(skill&&s.loadout.includes(skill.id)&&s.skills[skill.id],'Это умение не выбрано.');this.need(!(b.cooldowns[skill.id]>0),'Умение восстанавливается.');this.need(s.mana>=skill.mana,'Недостаточно маны.');}
 if(action.startsWith('item:')){const n=action.slice(5);this.need(this.count(n)&&D.items[n]?.effect,'Нет подходящего предмета.');}
 if(!['attack','guard','flee','relic','mirror','water'].includes(action)&&!action.startsWith('skill:')&&!action.startsWith('item:'))throw Error('Неизвестное действие.');
 if(action==='water')this.need(st.water&&!b.cooldowns.water&&s.mana>=10,'Водяной взрыв требует 10 маны и готовый Тризуб.');if(action==='mirror')this.need(st.mirror&&!b.cooldowns.mirror,'Зеркальный дар недоступен.');if(action==='relic')this.need(st.time&&!b.cooldowns.relic,'Реликвия недоступна.');
 for(const id in b.cooldowns)b.cooldowns[id]=Math.max(0,b.cooldowns[id]-1);
 if(b.heroEffects.stun){delete b.heroEffects.stun;this.log('Оглушение: герой пропускает действие.');}
 else if(action==='flee'){if(this.rng()<.65){b.result='escaped';s.coins=Math.max(0,s.coins-Math.ceil(s.coins*.02));this.log('Вы отступили. Потеряно 2% монет.');this.tick();return;}this.log('Отступить не удалось.');}
 else if(action==='attack'){power=1;s.mana=Math.min(st.mana,s.mana+4);}
 else if(action==='guard'){guard=true;s.mana=Math.min(st.mana,s.mana+10);this.log('Защитная стойка. +10 маны.');}
 else if(action==='water'){s.mana-=10;power=2;b.cooldowns.water=5;this.log('Тризуб вызывает водяной взрыв.');}
 else if(action==='mirror'){power=1.5;this.effect(b.enemyEffects,m.tier===2?'poison':m.tier===4?'burn':'slow',3,Math.round(b.attack*.3));b.cooldowns.mirror=5;this.log('Сет Изнанки отражает силу врага.');}
 else if(action==='relic'){this.effect(b.enemyEffects,'stun',2,0);b.cooldowns.relic=8;this.log('Песочные часы остановили врага.');}
 else if(action.startsWith('item:'))this.use(action.slice(5),true);
 else if(skill){s.mana-=skill.mana;b.cooldowns[skill.id]=skill.cooldown+1;const rank=s.skills[skill.id];this.log(skill.name+' · ранг '+rank);switch(skill.effect){
 case 'hit':power=1.5+(rank-1)*.15;break;case 'stun':power=.8;this.effect(b.enemyEffects,'stun',1,0);break;
 case 'dot':power=.6;this.effect(b.enemyEffects,s.cls==='mage'?'burn':'poison',3,Math.round(st.attack*(.22+rank*.04)));break;
 case 'heal':s.hp=Math.min(st.hp,s.hp+Math.round(st.hp*(.25+rank*.03)));break;case 'shield':b.shield=Math.round(st.hp*(.4+rank*.03));break;
 case 'power':this.effect(b.heroEffects,'power',4,.35+rank*.03);break;case 'execute':power=b.enemyHp/b.maxHp<.35?2.5:1.1;break;
 case 'freeze':this.effect(b.enemyEffects,'stun',1,0);power=.5;break;case 'drain':power=1.3;drain=.5;break;
 case 'counter':this.effect(b.heroEffects,'counter',2,.5);guard=true;break;case 'burst':power=2.3+rank*.1;break;
 case 'time':this.effect(b.enemyEffects,'slow',4,0);break;
 }}
 if(power){let damage=Math.max(1,Math.round(st.attack*power*(1+st.damageBoost+(b.heroEffects.power?.power||0))*(.9+this.rng()*.2)));if(this.rng()<st.crit){damage=Math.round(damage*1.7);this.log('Критический удар!');}if(st.undead&&m.tier===5)damage=Math.round(damage*(1+st.undead));b.enemyHp-=damage;this.log('Вы наносите '+damage+' урона.');s.hp=Math.min(st.hp,s.hp+Math.round(damage*(drain+st.lifesteal+(b.heroEffects.vampire?.power||0))));if(st.poison)this.effect(b.enemyEffects,'poison',3,st.poison);if(st.burn&&this.rng()<.25)this.effect(b.enemyEffects,'burn',3,Math.round(st.burn*(1+(st.fireBoost||0))));if(st.stun&&this.rng()<st.stun)this.effect(b.enemyEffects,'stun',1,0);if(st.summon||b.heroEffects.summon){b.enemyHp-=Math.round(st.attack*.2);this.log('Призванный скелет атакует.');}}
 b.turn++;this.tick();for(const [key,ef]of Object.entries(b.enemyEffects)){if(['poison','burn'].includes(key)){b.enemyHp-=ef.power;this.log((key==='poison'?'Яд':'Огонь')+': '+ef.power+' урона врагу.');}}
 if(b.enemyHp<=0){this.win();return;}
 const stunned=b.enemyEffects.stun,slow=b.enemyEffects.slow&&b.turn%2===0;
 if(stunned||slow)this.log(stunned?'Враг оглушён.':'Враг замедлен и пропускает ход.');else{
 const phase=m.boss?1+Math.min((m.name==='Истинная форма Бездны'?4:3)-1,Math.floor((1-b.enemyHp/b.maxHp)*(m.name==='Истинная форма Бездны'?4:3))):1;
 let raw=b.attack*(b.turn%3===0?1.65:1)*(1+(phase-1)*.12),ignore=m.name==='Призрак библиотекаря'?1:m.name==='Тень Бездны'?.5:0;
 let damage=Math.max(1,Math.round(raw-st.defense*.65*(1-ignore)));if(m.tier>=5)damage=Math.ceil(damage*(1-clamp(st.darkResist,0,.9)));if(guard)damage=Math.ceil(damage*.35);if(b.heroEffects.resist)damage=Math.ceil(damage*.7);if(this.rng()<st.dodge||b.heroEffects.invisible){damage=0;this.log('Уклонение.');}else if(this.rng()<st.block)damage=Math.ceil(damage*.5);if(b.shield>0){const absorbed=Math.min(b.shield,damage);damage-=absorbed;b.shield-=absorbed;}s.hp-=damage;b.damageTaken+=damage;this.log(m.name+': '+damage+' урона'+(b.turn%3===0?' · мощный удар':'')+'.');
 if(b.heroEffects.counter)b.enemyHp-=Math.round(damage*b.heroEffects.counter.power);
 if(damage>0){if(m.name==='Ползун-шахтёр')this.effect(b.heroEffects,'poison',3,Math.round(3*(1-st.poisonResist)));if(m.name==='Лавовый элементаль'&&!st.fireImmune&&!b.heroEffects.fireguard)this.effect(b.heroEffects,'burn',3,5);if(m.name==='Банши'&&b.turn%3===0)this.effect(b.heroEffects,'stun',2,0);if(m.name==='Зомби-слуга'||m.name==='Пожиратель Времени')s.mana=Math.max(0,s.mana-3);if(m.name==='Кровосос-вампир')b.enemyHp=Math.min(b.maxHp,b.enemyHp+Math.floor(damage*.4));}
 if(m.name==='Утопленник-страж')b.enemyHp=Math.min(b.maxHp,b.enemyHp+5);
 if(m.name==='Королева Ползунов'&&b.turn%4===0){s.hp-=9;b.damageTaken+=9;this.log('Три ползуна кусают героя: 9 урона.');}
 if(m.name==='Аватар Бездны'&&skill){s.hp-=8;b.damageTaken+=8;this.log('Аватар копирует магический след: 8 урона.');}
 }
 for(const [key,ef]of Object.entries(b.heroEffects))if(['poison','burn'].includes(key)){s.hp-=ef.power;b.damageTaken+=ef.power;this.log((key==='poison'?'Яд':'Поджог')+': −'+ef.power+' HP.');}
 for(const group of [b.enemyEffects,b.heroEffects])for(const [key,ef]of Object.entries(group)){ef.turns--;if(ef.turns<=0)delete group[key];}
 for(const n of Object.values(s.equipment))if(D.items[n]?.slot!=='pet')s.durability[n]=Math.max(0,(s.durability[n]??100)-.4);
 if(s.tier===5&&!st.curseImmune)s.curse=clamp(s.curse+2,0,100);this.cap();
 if(s.hp<=0){const revive=['Откат смерти','Свиток воскрешения'].find(n=>this.count(n));if(revive){this.remove(revive,1);s.hp=Math.round(st.hp*.5);this.log(revive+' спасает героя.');}else{b.result='loss';s.flawless=0;s.coins-=Math.floor(s.coins*.05);this.log('Поражение. Потеряно 5% монет. Вернитесь на площадь для отдыха.');}}
 if(!b.result&&b.enemyHp<=0)this.win();
 }
 win(){const s=this.s,b=s.battle;if(!b||b.result)return;const m=D.mobs.find(x=>x.id===b.id);b.result='win';b.enemyHp=0;s.kills[m.name]=(s.kills[m.name]||0)+1;s.flawless=b.damageTaken===0?s.flawless+1:0;if(/кирка/i.test(s.equipment.weapon||''))s.pickkills++;if(m.boss)s.bosses[m.id]=true;if(b.trial)s.trials++;
 for(const d of m.drops)if(this.rng()*100<this.chance(d)){const q=d[2]+Math.floor(this.rng()*(d[3]-d[2]+1));if(d[0]==='Медная монета'){s.coins+=q;}else {let n=d[0];if(n==='Легендарное оружие (1 из 3)')n=['Клинок пламени','Лук пламени','Посох пламени'][Math.floor(this.rng()*3)];if(n==='Копия лучшего предмета'){n=Object.values(s.equipment).sort((a,b)=>D.items[b].rarity-D.items[a].rarity)[0]||'Зеркальная копия предмета';}this.add(n,q);b.loot.push([n,q]);}}
 if(m.name==='Король-Лич Морат'){this.add('Печать Мората',3);b.loot.push(['Печать Мората',3]);}
 if(m.name==='Истинная форма Бездны'&&this.count('Эхо павших')>=5){this.add('Секретная концовка');b.loot.push(['Секретная концовка',1]);}
 if(m.name==='Вал’Гор'&&s.choices['4.5']==='Разорвать контракт'){this.add('Оружие против демонов');b.loot.push(['Оружие против демонов',1]);}const reward=35*m.tier*m.tier*(m.boss?4:1);s.coins+=m.tier*(m.boss?80:10);b.xp=reward;this.xp(reward);this.log('Победа! +'+reward+' опыта. Добыча получена.');this.say('Победа: '+m.name);this.achievements();}
 equip(n){this.idle();this.need(this.count(n)&&D.items[n]?.slot,'Этот предмет нельзя надеть.');this.s.equipment[D.items[n].slot]=n;this.cap();this.say('Надето: '+n);}
 use(n,battle=false){if(!battle)this.idle();this.need(this.count(n)>0,'Предмет закончился.');const it=D.items[n],eff=it.effect,s=this.s,st=this.stats(),b=s.battle&&!s.battle.result?s.battle:null;this.need(eff,'Этот предмет не расходуется вручную.');if(['blast','summon','shield','freeze','vampire','power','haste','resist','invisible','fireguard'].includes(eff))this.need(b,'Используйте этот предмет в бою.');
 if(eff==='hp')s.hp=Math.min(st.hp,s.hp+(n==='Хлеб'?20:Math.max(65,Math.round(st.hp*.35))));
 else if(eff==='mana')s.mana=Math.min(st.mana,s.mana+Math.max(45,Math.round(st.mana*.45)));
 else if(eff==='cleanse'){s.curse=0;if(b){delete b.heroEffects.poison;delete b.heroEffects.burn;delete b.heroEffects.stun;}}
 else if(eff==='antidote'){if(b)delete b.heroEffects.poison;}
 else if(eff==='breath')s.breath=20;
 else if(eff==='skill')s.skillPoints++;
 else if(eff==='blast')b.enemyHp-=Math.round(st.attack*2);
 else if(eff==='shield')b.shield+=Math.round(st.hp*.4);
 else if(eff==='freeze')this.effect(b.enemyEffects,'stun',2,0);
 else if(eff==='vampire')this.effect(b.heroEffects,'vampire',6,.15);
 else if(eff==='haste')this.effect(b.enemyEffects,'slow',4,0);
 else if(['power','resist','invisible','fireguard','summon'].includes(eff))this.effect(b.heroEffects,eff,4,eff==='power'?.35:1);
 else if(eff==='divine'){s.hp=st.hp;s.mana=st.mana;s.curse=0;}
 else if(eff==='revive'){s.hp=st.hp;}
 else if(eff==='chest'){const pool=Object.values(D.items).filter(x=>x.rarity===4);this.add(pool[Math.floor(this.rng()*pool.length)].name);}
 this.remove(n,1);if(b)this.log('Использовано: '+n);else this.say('Использовано: '+n);}
 learn(id){this.idle();const s=this.s,a=D.skills.find(x=>x.id===id);this.need(a&&a.cls===s.cls,'Чужой класс.');this.need(s.level>=a.level,'Требуется уровень '+a.level);this.need(s.skillPoints>0,'Нет очков навыков.');this.need((s.skills[id]||0)<3,'Максимальный ранг — 3.');s.skills[id]=(s.skills[id]||0)+1;s.skillPoints--;if(!a.passive&&s.loadout.length<6&&!s.loadout.includes(id))s.loadout.push(id);}
 toggle(id){this.idle();this.need(this.s.skills[id]&&!D.skills.find(x=>x.id===id).passive,'Умение не изучено.');if(this.s.loadout.includes(id))this.s.loadout=this.s.loadout.filter(x=>x!==id);else{this.need(this.s.loadout.length<6,'Можно подготовить до 6 умений.');this.s.loadout.push(id);}}
 allocate(k){this.idle();this.need(Object.keys(this.s.stats).includes(k)&&this.s.statPoints>0,'Нет очков характеристик.');this.s.stats[k]++;this.s.statPoints--;}
 craft(id){this.idle();const r=D.recipes.find(x=>x.id===id);this.need(r,'Рецепт не найден.');this.need(this.s.tier===r.tier,'Нужна мастерская яруса '+r.tier);for(const [n,q]of Object.entries(r.cost))this.need(this.count(n)>=q,'Не хватает: '+n);for(const [n,q]of Object.entries(r.cost))this.remove(n,q);let qty=r.qty;if(this.rng()<(this.s.flags.craftBonus||0))qty++;this.add(r.output,qty);this.s.crafts+=qty;this.say('Создано: '+r.output+' ×'+qty);}
 repair(n){this.idle();this.need(this.count(n)&&D.items[n].slot,'Нет снаряжения.');this.need(this.s.tier===1||this.s.tier===4,'Ремонт доступен у Грима или Тарна.');const cost=Math.max(1,Math.ceil(this.price(n)*.1*(1-this.discount())));this.need(this.s.coins>=cost,'Не хватает монет.');this.s.coins-=cost;this.s.durability[n]=100;this.say('Предмет отремонтирован за '+cost+' меди.');}
 upgrade(n){this.idle();this.need(this.count(n)&&['weapon','armor'].includes(D.items[n].slot),'Улучшать можно оружие и броню.');const u=this.s.upgrades[n]||0,max=this.s.tier===7?10:this.s.tier===4?5:this.s.tier===1?3:0;this.need(u<max,'Здесь недоступно следующее улучшение.');const cost=[1000,3000,10000,50000,150000,180000,220000,260000,300000,350000][u];this.need(this.s.coins>=cost,'Нужно '+cost+' меди.');this.s.coins-=cost;this.s.upgrades[n]=u+1;this.say(n+' улучшен до +'+(u+1));}
 price(n){const row=D.shops.filter(s=>s.currency==='coins').flatMap(s=>s.goods).find(g=>g[0]===n);return row?row[1]:Math.max(5,(D.items[n]?.rarity+1||1)*25*(D.items[n]?.tier||1));}
 shopOpen(shop){if(shop.rule==='fox')return this.s.flags.foxTier===this.s.tier&&this.s.flags.foxDay===this.s.day?'':'Лис встречается при обыске и исчезает на следующий день';if(['teacher','brother','sister'].includes(shop.rule)&&!this.s.flags[shop.rule])return 'Торговец ещё не спасён';if(shop.rule==='weekly'&&(this.s.day-1)%7!==0)return 'Старый Маг приходит в дни 1, 8, 15…';if(this.s.tier!==shop.tier)return 'Нужен ярус '+shop.tier;if(shop.rule==='night'&&this.s.hour>=6&&this.s.hour<20)return 'Появляется ночью: 20:00–06:00';if(shop.rule==='third'&&(this.s.day-1)%3!==0)return 'Хрон появляется в дни 1, 4, 7…';return '';}
 buy(sid,index){this.idle();const sh=D.shops.find(x=>x.id===sid),row=sh?.goods[index];this.need(row,'Нет такого товара.');this.need(!this.shopOpen(sh),this.shopOpen(sh));const [n,base,rep]=row;this.need(this.s.rep>=rep,'Недостаточно репутации.');let amount=Math.ceil(base*(sh.currency==='coins'?1-Math.max(this.discount(),this.s.flags[sh.id+'Discount']||0):1));if(sh.id==='librarian'&&this.s.flags.freeScrolls&&n.startsWith('Свиток'))amount=0;
 if(sh.currency==='coins'){this.need(this.s.coins>=amount,'Не хватает монет.');this.s.coins-=amount;}
 else if(sh.currency==='legendary'){const pool=Object.keys(this.s.inventory).filter(n=>D.items[n]?.rarity===4&&!Object.values(this.s.equipment).includes(n));this.need(pool.reduce((a,n)=>a+this.count(n),0)>=amount,'Нужны ненадетые легендарные предметы.');for(const n of pool){const used=Math.min(amount,this.count(n));this.remove(n,used);amount-=used;if(!amount)break;}}
 else this.remove(sh.currency,amount);this.add(sh.rule==='fox'&&this.rng()<.3?'Подделка Лиса':n);this.say('Получено у торговца: '+n);}
 sell(n){this.idle();this.need(this.count(n)>0,'Нет предмета.');this.need(!Object.values(this.s.equipment).includes(n),'Сначала снимите предмет.');this.need(!/ключ|дыхание бездны|книга тар-морана|осколок изнанки/i.test(n),'Этот предмет нужен для путешествия.');this.remove(n,1);this.s.coins+=Math.max(1,Math.floor(this.price(n)*.4));}
 service(type,n=''){this.idle();const s=this.s;if(type==='copy'){this.need(s.tier===6,'Нужен Хранитель Зеркал.');this.need(this.count(n)&&D.items[n].slot,'Выберите предмет экипировки.');this.remove('Осколок зеркала',100);this.add(n);this.say('Создана копия: '+n);}else if(type==='appearance'){this.need(s.tier===6,'Нужен Хранитель Зеркал.');this.remove('Осколок зеркала',20);s.flags.appearance=((s.flags.appearance||0)+1)%3;this.say('Хранитель изменил облик героя.');}else if(type==='respec'){this.need(s.tier===7,'Нужен Аватар Бездны.');this.remove('Слеза Бездны',20);s.skillPoints+=Object.values(s.skills).reduce((a,b)=>a+b,0);s.skills={};s.loadout=[];this.say('Очки умений возвращены.');}else if(type==='upgrade10'){this.need(s.tier===7,'Нужен Аватар Бездны.');this.need(this.count(n)&&['weapon','armor'].includes(D.items[n].slot),'Выберите оружие или броню.');this.remove('Слеза Бездны',100);s.upgrades[n]=10;this.say('Улучшено до +10: '+n);}else if(type==='tail'){this.need(s.tier===2,'Нужен Борин.');this.remove('Крысиный хвост',5);this.add('Малое зелье HP');}else if(type==='bone'){this.need(s.tier===5,'Нужен Ваэлор.');this.remove('Кость',20);this.add('Эликсир очищения');}this.cap();}
 wait(){this.idle();this.tick();this.say('Прошёл час. День '+this.s.day+', '+this.s.hour+':00.');}
 convert(rarity){this.idle();const rules={0:[100,2,5],1:[10,2,4],2:[5,3,3],3:[3,4,6]},rule=rules[rarity];this.need(rule&&this.s.tier>=rule[2],'Обмен пока недоступен.');const pool=Object.keys(this.s.inventory).filter(n=>D.items[n]?.rarity===rarity&&!Object.values(this.s.equipment).includes(n)&&!(/ключ|дыхание|книга тар-морана|осколок изнанки/i.test(n)));this.need(pool.reduce((a,n)=>a+this.count(n),0)>=rule[0],'Не хватает предметов редкости.');let need=rule[0];for(const n of pool){const q=Math.min(need,this.count(n));this.remove(n,q);need-=q;if(!need)break;}const options=Object.values(D.items).filter(x=>x.rarity===rule[1]&&x.tier<=this.s.tier&&x.slot);this.need(options.length,'Нет подходящих предметов.');const chosen=options[Math.floor(this.rng()*options.length)].name;this.add(chosen);this.say('Обмен редкости: '+chosen);}
 questLock(q){const s=this.s;if(s.quests[q.id]?.done)return 'Завершено';if(s.level<q.level)return 'Уровень '+q.level;if(s.rep<q.rep)return 'Репутация '+q.rep;if(q.prerequisites.some(id=>!s.quests[id]?.done))return 'Завершите: '+q.prerequisites.join(', ');if(q.id==='4.5'&&total(s.kills)<100)return 'Победите 100 врагов';if(q.id==='2.4'&&(total(s.kills)<50||(s.hour>=6&&s.hour<20)))return '50 побед и ночное время';if(q.id==='1.2'&&s.choices['1.1']==='Солгать')return 'Корин не узнал правду. Ветка закрыта до NG+.';return '';}
 accept(id){this.idle();const q=D.quests.find(x=>x.id===id);this.need(q,'Нет задания.');this.need(this.s.tier===q.tier,'Поговорите с NPC на ярусе '+q.tier);this.need(!this.questLock(q),this.questLock(q));this.need(!this.s.quests[id],'Задание уже принято.');this.s.quests[id]={done:false,baseKills:{...this.s.kills},baseExplore:{...this.s.explored},baseCraft:this.s.crafts,basePick:this.s.pickkills};this.say('Задание принято: '+q.name);}
 progress(q){const s=this.s,active=s.quests[q.id];return q.goals.map(([t,n,target])=>{let value=0;if(t==='item')value=this.count(n);if(t==='kill')value=n==='*'?total(s.kills)-total(active?.baseKills||{}):(s.kills[n]||0)-(active?.baseKills?.[n]||0);if(t==='explore')value=(s.explored[n]||0)-(active?.baseExplore?.[n]||0);if(t==='craft')value=s.crafts-(active?.baseCraft||0);if(t==='pickkills')value=s.pickkills-(active?.basePick||0);if(t==='flawless')value=s.flawless;if(t==='completion')value=Object.entries(s.quests).filter(([id,v])=>v.done&&id!=='7.3').length;return {type:t,name:n,target,value:clamp(value,0,target),done:value>=target};});}
 complete(id,choice=''){this.idle();const s=this.s,q=D.quests.find(x=>x.id===id),a=s.quests[id];this.need(q&&a&&!a.done,'Задание недоступно.');this.need(s.tier===q.tier,'Вернитесь к NPC на ярусе '+q.tier);this.need(this.progress(q).every(g=>g.done),'Цели ещё не выполнены.');this.need(!q.choices.length||q.choices.includes(choice),'Выберите решение.');if(id==='3.2'&&choice==='Выкупить сестру')this.need(s.coins>=1000,'Для выкупа нужно 10 серебра.');for(const [t,n,c]of q.goals)if(t==='item')this.remove(n,c);a.done=true;s.choices[id]=choice;s.coins+=q.money;s.rep+=q.reputation;for(const[n,c]of Object.entries(q.rewards))this.add(n,c);this.xp(100*q.tier*q.tier);this.say('Завершено: '+q.name+(choice?' · '+choice:''));
 const grant=(n)=>this.add(n);switch(id){
 case '1.1':if(choice==='Солгать'){s.coins+=300;s.rep-=30;}break;
 case '1.2':if(choice==='Пощадить'){this.remove('Крысиный король (питомец)',1);grant('Крысиный амулет');}break;
 case '1.3':s.flags.secretChest=true;grant('Ядро голема');break;
 case '1.4':if(choice==='Оставить молот'){grant('Кузнечный молот');s.rep-=45;}else if(s.equipment.weapon)s.upgrades[s.equipment.weapon]=Math.max(1,s.upgrades[s.equipment.weapon]||0);break;
 case '1.6':s.flags.craftBonus=(s.flags.craftBonus||0)+.05;break;
 case '1.9':s.flags.teacher=choice==='Спасти учителя';if(!s.flags.teacher)grant('Рецепт учителя');break;
 case '2.2':grant(choice==='Освободить брата'?'Амулет братства':'Кирка брата');s.flags.brother=choice==='Освободить брата';break;
 case '2.3':s.flags.borinDiscount=.5;break;
 case '2.4':grant(choice==='Принять сделку'?'Проклятый амулет':'Благословение');break;
 case '3.2':if(choice==='Выкупить сестру'){s.coins-=1000;s.flags.sister=true;}else grant('Глаз левиафана');break;
 case '3.3':s.flags.moonSecret=true;break;
 case '3.6':if(choice==='Освободить призрака')grant('Архивный том');else s.flags.freeScrolls=true;break;
 case '4.2':if(choice==='Исцелить Тарна')s.flags.tarnDiscount=.3;else{s.flags.craftBonus=(s.flags.craftBonus||0)+.5;s.rep-=125;}break;
 case '4.4':s.flags.tarnDiscount=.5;break;
 case '4.5':if(choice==='Разорвать контракт')this.start(D.mobs.find(m=>m.name==='Вал’Гор').id);break;
 case '4.6':grant(choice==='Помочь Легиону'?'Адская броня':'Оружие против демонов');break;
 case '5.2':if(choice==='Освободить души')grant('Благословение');else this.add('Душа банши',5);break;
 case '5.4':grant(choice==='Освободить Мората'?'Полный сет «Морат»':'Морат-питомец');break;
 case '6.2':grant(choice==='Принять себя'?'Зеркальный двойник (питомец)':'Третий глаз');break;
 case '6.3':grant(choice==='Освободить Изнанку'?'Сет «Изнанка» (4 части)':'Око Бездны');break;
 case '6.5':if(choice==='Освободить Хрона'){this.add('Эликсир ускорения',3);s.flags.chronAlly=true;}else grant('Откат смерти');break;
 case '6.7':s.flags.secretEnding=choice;break;
 case '7.1':s.ending=choice;break;
 case '7.3':s.flags.ngReady=true;break;
 }this.achievements();}
 achievements(){const s=this.s,n=Object.values(s.quests).filter(x=>x.done).length;for(const [name,req,reward]of [['Помощник',10,100],['Герой города',25,500],['Легенда',41,10000]])if(n>=req&&!s.achievements[name]){s.achievements[name]=true;s.coins+=reward;this.say('Достижение: '+name);}if(['6.4','6.5','6.6','6.7'].every(id=>s.quests[id]?.done)&&!s.achievements['Хранитель времени']){s.achievements['Хранитель времени']=true;this.add('Часы Хрона');}if(['Полный сет «Морат»','Сет «Изнанка» (4 части)','Наследие Тар-Морана · выкованный'].every(n=>this.count(n))&&!s.achievements['Наследник']){s.achievements['Наследник']=true;this.add('Наследие Тар-Морана');}const evil={'1.1':'Солгать','1.9':'Убить учителя','2.2':'Убить брата','3.6':'Оставить призрака','4.2':'Усилить проклятие','4.6':'Помочь Легиону','5.4':'Подчинить Мората','6.3':'Подчинить Изнанку'};if(Object.entries(evil).every(([id,c])=>s.choices[id]===c)&&!s.achievements['Тёмный путь']){s.achievements['Тёмный путь']=true;this.add('Проклятый сет');}}
 ngPlus(keep=true){this.idle();this.need(this.s.ending,'Сначала завершите «Сердце Бездны».');if(!this.s.flags.ngReady)this.remove('Слеза Бездны',500);const old=this.s;this.create(old.name,old.cls);const s=this.s;s.ng=old.ng+1;if(keep){s.level=old.level;s.stats=old.stats;s.inventory=old.inventory;s.equipment=old.equipment;s.skills=old.skills;s.loadout=old.loadout;s.skillPoints=old.skillPoints;s.statPoints=old.statPoints;s.durability=old.durability;s.upgrades=old.upgrades;s.flags.memories=old.choices;}s.hp=this.stats().hp;s.mana=this.stats().mana;this.say('Новый цикл Бездны '+s.ng+'. Враги сильнее; история началась заново.');}
 export(){return JSON.stringify(this.s,null,2);}
 static validate(v){if(!v||v.version!==2||!D.classes[v.cls]||typeof v.name!=='string'||v.name.length>24)throw Error('Это не сохранение Тар-Морана версии 2.');for(const k of ['level','xp','hp','mana','coins','rep','tier','day','hour','turns','curse','breath','statPoints','skillPoints','crafts','pickkills','flawless','trials','ng'])if(!Number.isFinite(v[k]))throw Error('Повреждено поле '+k);if(v.level<1||v.level>60||v.tier<1||v.tier>7||!D.zones[v.tier-1].rooms.includes(v.room))throw Error('Неверная локация или уровень.');for(const k of ['inventory','equipment','durability','upgrades','stats','skills','kills','explored','bosses','quests','choices','achievements','flags'])if(!v[k]||typeof v[k]!=='object'||Array.isArray(v[k]))throw Error('Повреждено '+k);for(const[n,q]of Object.entries(v.inventory))if(!D.items[n]||!Number.isInteger(q)||q<0)throw Error('Повреждён инвентарь.');for(const[k,n]of Object.entries(v.equipment))if(!slots.includes(k)||D.items[n]?.slot!==k||!v.inventory[n])throw Error('Неверная экипировка.');for(const k of ['strength','agility','intellect','vitality','luck'])if(!Number.isFinite(v.stats[k])||v.stats[k]<0)throw Error('Неверные характеристики.');if(!Array.isArray(v.loadout)||v.loadout.length>6||v.loadout.some(id=>!D.skills.some(a=>a.id===id&&a.cls===v.cls&&!a.passive)||!v.skills[id]))throw Error('Неверные умения.');if(!Array.isArray(v.feed)||v.feed.some(x=>typeof x!=='string'))throw Error('Неверный журнал.');if(v.battle){const b=v.battle;if(!D.mobs.some(m=>m.id===b.id)||!Number.isFinite(b.enemyHp)||!Number.isFinite(b.maxHp)||!Number.isFinite(b.attack)||!Number.isFinite(b.turn)||!Array.isArray(b.logs)||b.logs.some(x=>typeof x!=='string')||!b.cooldowns||!b.enemyEffects||!b.heroEffects)throw Error('Повреждено сохранение боя.');}return v;}
}
root.TM_Game=Game;if(typeof module!=='undefined')module.exports=Game;
})(globalThis);
