const assert=require('node:assert/strict');require('./data.js');const Game=require('./engine.js'),D=TM_DATA;let count=0;
function test(n,f){try{f();console.log('PASS',n);count++;}catch(e){console.error('FAIL',n,e);process.exitCode=1;}}
const fresh=(cls='warrior',r=.5)=>{const g=new Game(null,()=>r);g.create('Проверка',cls);return g;};
const mob=n=>D.mobs.find(m=>m.name===n).id;
test('Data completeness and references',()=>{assert.equal(D.quests.length,41);assert.equal(D.recipes.length,27);assert.equal(D.mobs.length,29);assert.equal(D.skills.length,72);for(const r of D.recipes){assert(D.items[r.output],r.output);for(const n in r.cost)assert(D.items[n],n);}for(const q of D.quests){for(const n in q.rewards)assert(D.items[n],n);for(const p of q.prerequisites)assert(D.quests.some(q=>q.id===p));}});
test('Creation, manual victory, guaranteed loot, no duplicate reward',()=>{for(const cls of Object.keys(D.classes)){const g=fresh(cls);g.start(mob('Гигантская крыса-мутант'));for(let i=0;i<10&&!g.s.battle.result;i++)g.act('attack');assert.equal(g.s.battle.result,'win');assert(g.count('Крысиный хвост'));const xp=g.s.xp;g.win();assert.equal(g.s.xp,xp);assert.throws(()=>g.act('attack'));}});
test('Cooldown and mana are validated before any mutation',()=>{const g=fresh();g.start(mob('Каменный Страж'));g.act('skill:warrior0');const before=g.export();assert.throws(()=>g.act('skill:warrior0'));assert.equal(g.export(),before);assert.throws(()=>g.travel(1,'Казармы'));});
test('No early zone unlock',()=>{const g=fresh();assert(g.gate(2));g.s.level=5;assert(g.gate(2));g.s.bosses[mob('Каменный Страж')]=true;assert.equal(g.gate(2),'');g.travel(2,'Главный ствол');assert.equal(g.s.tier,2);});
test('Quest acceptance counts only subsequent kills, consumption once',()=>{const g=fresh();g.s.kills['Гигантская крыса-мутант']=5;g.accept('1.1');assert.equal(g.progress(D.quests[0])[1].value,0);g.s.kills['Гигантская крыса-мутант']+=3;g.s.explored['Подвалы']=1;g.complete('1.1','Сказать правду');assert(g.s.quests['1.1'].done);assert.throws(()=>g.complete('1.1','Сказать правду'));});
test('Every recipe crafts and provides a usable result',()=>{for(const r of D.recipes){const g=fresh();g.s.tier=r.tier;for(const[n,q]of Object.entries(r.cost))g.add(n,q);g.craft(r.id);assert(g.count(r.output)>=r.qty,r.name);assert(D.items[r.output].slot||D.items[r.output].effect,'Unusable recipe '+r.name);}});
test('Every quest completion and choice branch runs',()=>{for(const q of D.quests)for(const choice of q.choices.length?q.choices:['']){const g=fresh();g.s.level=40;g.s.rep=1000;g.s.coins=100000;g.s.tier=q.tier;g.s.room=D.zones[q.tier-1].rooms[0];g.s.hour=23;g.s.kills.Test=100;for(const pre of q.prerequisites)g.s.quests[pre]={done:true};g.accept(q.id);for(const[t,n,c]of q.goals){if(t==='item')g.add(n,c);if(t==='kill'){if(n==='*')g.s.kills.Test+=c;else g.s.kills[n]=(g.s.kills[n]||0)+c;}if(t==='explore')g.s.explored[n]=c;if(t==='craft')g.s.crafts=c;if(t==='pickkills')g.s.pickkills=c;if(t==='flawless')g.s.flawless=c;if(t==='completion')for(const other of D.quests)if(other.id!==q.id)g.s.quests[other.id]={done:true};}g.complete(q.id,choice);assert(g.s.quests[q.id].done,q.id);}});
test('Save roundtrip with active battle and reject damaged import',()=>{const g=fresh();g.start(mob('Каменный Страж'));g.act('guard');const copy=new Game(Game.validate(JSON.parse(g.export())));assert.equal(copy.export(),g.export());assert.throws(()=>Game.validate({version:2}));const v=JSON.parse(g.export());v.inventory.Unknown=1;assert.throws(()=>Game.validate(v));});
test('Defeat, return and restore',()=>{const g=fresh();g.s.hp=1;g.start(mob('Каменный Страж'));g.act('attack');assert.equal(g.s.battle.result,'loss');assert.equal(g.s.hp,0);g.rest();assert.equal(g.s.hp,g.stats().hp);});
test('Shop stock, barter and recipe ingredient reachability',()=>{const sources=new Set(D.mobs.flatMap(m=>m.drops.map(d=>d[0])).concat(D.shops.flatMap(s=>s.goods.map(g=>g[0])),Object.values(D.gather).flat().map(g=>g[0]),D.quests.flatMap(q=>Object.keys(q.rewards)),D.recipes.map(r=>r.output)));for(const r of D.recipes)for(const n of Object.keys(r.cost))assert(sources.has(n),'No source for '+n);});
console.log('Completed',count,'tests');
